# Generated by Django 5.0.6 on 2024-07-23 09:44

import django.db.models.deletion
import pgvector.django
import playground.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_ver2',
            fields=[
                ('vector_product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productDes', models.TextField()),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('sold_units', models.IntegerField()),
                ('rating', models.FloatField()),
                ('no_review', models.IntegerField()),
                ('link', models.URLField()),
                ('shipmentOrigin', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('productName_embed', pgvector.django.VectorField(default=playground.models.default_vector, dimensions=384)),
            ],
        ),
        migrations.CreateModel(
            name='LangchainPgEmbedding_ver2',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
                ('document', models.CharField(blank=True, max_length=1000, null=True)),
                ('cmetadata', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='playground.product_ver2')),
            ],
        ),
    ]
